<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sdl</string>
		<string>sdt</string>
		<string>spd</string>
		<string>sdt</string>
		<string>sst</string>
		<string>sed</string>
	</array>
	<key>name</key>
	<string>tnsdl</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>TNSDL type keyword</string>
			<key>match</key>
			<string>\b(COMMENT|STRUCT|ENDSTRUCT|TO|OUTPUT|NEXTSTATE|FPAR|CALL|TASK|PROGRAMBLOCK|IMPLEMENTATION|ENDIMPLEMENTATION|MODULE|ENDPROCEDURE|START|RETURNS)\b</string>
			<key>name</key>
			<string>keyword.source.tnsdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(NIL|T|F|pid|word|dword|byte|bool|bytepointer|[a-zA-Z]+[a-zA-Z0-9_]*_t)\b</string>
			<key>name</key>
			<string>storage.type.tnsdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>:=</string>
			<key>name</key>
			<string>keyword.operator.assignment.tnsdl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>TNSDL type keyword</string>
			<key>match</key>
			<string>\b(PRIORITY|DESTROY_MSG_IF_NOT_WO_STATE|[a-zA-Z]+[a-zA-Z0-9_]*_ec|[a-zA-Z]+[a-zA-Z0-9_]*_c|SENDER_PHYS_COMPUTER|SENDER|CONSTANT|ENDTYPE|REPRESENTATION)\b</string>
			<key>name</key>
			<string>constant.language.tnsdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(=|&lt;|&gt;|&gt;=|&lt;=|/=)</string>
			<key>name</key>
			<string>keyword.operator.comparison.tnsdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(DECISION|ELSE|ENDDECISION|WHILE|ENDWHILE|RETURN)\b</string>
			<key>name</key>
			<string>keyword.control.tnsdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(SET|-\&gt;|\+|\-|ADDPTR|POINTER|AND|OR|NOT|SIZEOF)\b</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.tnsdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(DCL|SAVE|WITHWARMING|IN|OUT)\b</string>
			<key>name</key>
			<string>storage.modifier.tnsdl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.tnsdl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.tnsdl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tnsdl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(PROCEDURE)\s+([a-zA-Z_]\w*);</string>
			<key>name</key>
			<string>meta.function.tnsdl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.tnsdl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tnsdl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(INPUT)\s+([a-zA-Z_]\w*)</string>
			<key>name</key>
			<string>meta.function.tnsdl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.any-method.tnsdl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.tnsdl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([a-zA-Z_]\w*)\s*\((.*)\)</string>
			<key>name</key>
			<string>meta.function.tnsdl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.tnsdl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tnsdl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(SIGNAL)\s+([a-zA-Z_][a-zA-Z0-9_]*)</string>
			<key>name</key>
			<string>meta.function.tnsdl</string>
		</dict>

		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.tnsdl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tnsdl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(TYPE)\s+([a-zA-Z_][a-zA-Z0-9_]*)</string>
			<key>name</key>
			<string>meta.function.tnsdl</string>
		</dict>
		
		<dict>
			<key>match</key>
			<string>,</string>
			<key>name</key>
			<string>punctuation.seperator.property.tnsdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(0(x|X)[0-9a-fA-F]+)\b</string>
			<key>name</key>
			<string>constant.numeric.tnsdl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.tnsdl</string>
	<key>uuid</key>
	<string>8850f81b-44db-4ea2-ae88-71f352d66787</string>
</dict>
</plist>
